apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jupyter-notebook
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: jupyter-notebook
    spec:
      containers:
      - name: oauth-proxy
        image: gurvin/oauth-proxy
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        volumeMounts:
          - mountPath: /oauth-proxy/config
            name: oauth-proxy-config
      - name: jupyter-notebook
        image: jupyter/notebook:4.2.0
        volumeMounts:
          - name: notebooks
            mountPath: /notebooks
          - name: notebook-config
            mountPath: /root/.jupyter
      volumes:
        - name: notebooks
          persistentVolumeClaim:
            claimName: nfs
        - name: notebook-config
          configMap:
            name: jupyter-notebook
            items:
            - key: jupyter-notebook-config.py
              path: jupyter_notebook_config.py
        - name: oauth-proxy-config
          configMap:
            name: notebook-oauth-proxy
            items:
            - key: oauth-proxy.json
              path: oauth-proxy.json