apiVersion: v1
kind: PersistentVolume
metadata:
  name: owncloud-nfs
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 10.240.0.8
    path: "/exports/data"

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: owncloud-nfs
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi